### ISSUE TITLE
Build failed for a new Ember app

### ISSUE THREAD

**Issue by ronny35** [projectcaluma/ember-caluma#570]
Hello,

I would import ember-caluma for a new project but build failed.

Step 1:
ember new project && cd project

Step 2:
yarn install && ember install ember-caluma
==> Need ember-engines so
npm install ember-engines

Step 3:
ember build

![captur](https://user-images.githubusercontent.com/15168987/66223739-7f9d9600-e6d4-11e9-8636-06f1c5f8f286.png)

Thanks in advance for your help.

**Comment by czosel** [comment]
Hi @ronny35,

When I tried to reproduce the issue locally I got a different exception (`Cannot find module 'ember-engines/lib/engine-addon'`). I was able to get it to work by installing ember-engines first though:

```bash
ember new project && cd project
ember install ember-engines
ember install ember-caluma
ember build
```

We'll definitely have to check why a simple `ember install ember-caluma` doesn't work as expected, but in the meantime you might be able to solve the issue by running the above commands. If it doesn't work, please share the exact commands you ran so that we can try and reproduce the issue, together with some information about your environment (ember-cli version, node version, operating system).

**Comment by ronny35** [comment]
Hello,

Thanks for your response. This issue appears when I run `ember install caluma` before `ember install ember-caluma`.
Your recommandations works.
